archivotarea:
    pattern:  /
    defaults: { _controller: "HeraContadoresBundle:ArchivoTarea:index" }

archivotarea_show:
    pattern:  /{id}/show
    defaults: { _controller: "HeraContadoresBundle:ArchivoTarea:show" }

archivotarea_new:
    pattern:  /new
    defaults: { _controller: "HeraContadoresBundle:ArchivoTarea:new" }

archivotarea_create:
    pattern:  /create
    defaults: { _controller: "HeraContadoresBundle:ArchivoTarea:create" }
    requirements: { _method: post }

archivotarea_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "HeraContadoresBundle:ArchivoTarea:edit" }

archivotarea_update:
    pattern:  /{id}/update
    defaults: { _controller: "HeraContadoresBundle:ArchivoTarea:update" }
    requirements: { _method: post|put }

archivotarea_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "HeraContadoresBundle:ArchivoTarea:delete" }
    requirements: { _method: post|delete }
