security:
    providers:
        in_memory:
            memory: ~

        db_provider:
            entity:
                class: ContadoresBundle:Usuario
                property: mail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
            provider: db_provider
            form_login:
                login_path:     /login
                check_path:     /login_check
                csrf_provider:  security.csrf.token_manager
                default_target_path: default_security_target
            logout:
                path:   /logout
                target: /login

    # CAMBIAR ESTO PARA AGREGAR LOS DISTINTOS ROLES Y ACCESOS CORRESPONDIENTES
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/redirect, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/home, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/en_construccion, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/cambiar_password, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/logout, roles: IS_AUTHENTICATED_FULLY }

        - { path: ^/(.+), roles: IS_AUTHENTICATED_FULLY }

    encoders:
        ContadoresBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 12

    access_denied_url: /unauthorized
