security:
    providers:
        in_memory:
            memory: ~

        db_provider:
            entity:
                class: ContadoresBundle:Usuario
                property: mail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
            provider: db_provider
            form_login:
                login_path:     /login
                check_path:     /login_check
                csrf_provider:  security.csrf.token_manager
                default_target_path: default_security_target
            logout:
                path:   /logout
                target: /login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/usuario, roles: [ROLE_ADMIN] }
        - { path: ^/contador, roles: [ROLE_ADMIN, ROLE_JEFE, ROLE_CONTADOR] }
        - { path: ^/tipoestado, roles: [ROLE_ADMIN] }
        - { path: ^/cliente, roles: [ROLE_ADMIN, ROLE_JEFE, ROLE_CONTADOR] }
        - { path: ^/tarea, roles: [ROLE_ADMIN, ROLE_JEFE, ROLE_CONTADOR, ROLE_CLIENTE] }
        - { path: ^/tareametadata, roles: [ROLE_ADMIN, ROLE_JEFE] }
        - { path: ^/area, roles: [ROLE_ADMIN, ROLE_JEFE, ROLE_CONTADOR] }
        - { path: ^/rubro, roles: [ROLE_ADMIN, ROLE_JEFE] }
        - { path: ^/contador, roles: [ROLE_ADMIN, ROLE_JEFE] }
        - { path: ^/vencimiento, roles: [ROLE_ADMIN, ROLE_JEFE] }
        - { path: ^/reporte, roles: [ROLE_ADMIN, ROLE_JEFE] }

        - { path: ^/archivoZip, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/redirect, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/home, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/en_construccion, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/cambiar_password, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/logout, roles: IS_AUTHENTICATED_FULLY }

        - { path: ^/(.+), roles: ROLE_ADMIN }

    encoders:
        ContadoresBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 12

    access_denied_url: /unauthorized
