hera_contadores_vencimiento:
    resource: "@HeraContadoresBundle/Resources/config/routing/vencimiento.yml"
    prefix:   /vencimiento

hera_contadores_archivometadata:
    resource: "@HeraContadoresBundle/Resources/config/routing/archivometadata.yml"
    prefix:   /archivometadata

hera_contadores_archivotarea:
    resource: "@HeraContadoresBundle/Resources/config/routing/archivotarea.yml"
    prefix:   /archivotarea

hera_contadores_archivocliente:
    resource: "@HeraContadoresBundle/Resources/config/routing/archivocliente.yml"
    prefix:   /archivocliente

hera_contadores_archivo:
    resource: "@HeraContadoresBundle/Resources/config/routing/archivo.yml"
    prefix:   /archivo

hera_contadores_observacion:
    resource: "@HeraContadoresBundle/Resources/config/routing/observacion.yml"
    prefix:   /observacion

hera_contadores_homepage:
    path:     /hello/{name}
    defaults: { _controller: HeraContadoresBundle:Default:index }
