ContadoresBundle\Entity\ArchivoTarea:
    type: entity
    table: archivo_tarea
    indexes:
        usuario_archivoT_idx:
            columns:
                - usuario_id
        tarea_archivo_idx:
            columns:
                - tarea_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        ruta:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
    manyToOne:
        tarea:
            targetEntity: Tarea
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tarea_id:
                    referencedColumnName: id
            orphanRemoval: false
        usuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
