ContadoresBundle\Entity\ArchivoSubTarea:
    type: entity
    table: archivo_sub_tarea
    indexes:
        usuario_archivo_idx:
            columns:
                - usuario_id
        subTarea_archivo_idx:
            columns:
                - sub_tarea_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        ruta:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
    manyToOne:
        subTarea:
            targetEntity: SubTarea
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sub_tarea_id:
                    referencedColumnName: id
            orphanRemoval: false
        usuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
