ContadoresBundle\Entity\Archivo:
    type: entity
    table: archivo
    indexes:
        fk_archivo_usuario_idx:
            columns:
                - usuario_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        ruta:
            type: string
            nullable: false
            length: 75
            options:
                fixed: false
        creationTime:
            type: datetime
            nullable: false
            column: creation_time
        updateTime:
            type: datetime
            nullable: false
            column: update_time
        fileSize:
            type: integer
            nullable: false
            column: file_size
    manyToOne:
        usuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
