ContadoresBundle\Entity\ArchivoMetadata:
    type: entity
    table: archivo_metadata
    indexes:
        tareaMetadata_archivo_idx:
            columns:
                - tarea_metadata_id
        archivo_metadata_idx:
            columns:
                - archivo_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        tareaMetadata:
            targetEntity: TareaMetadata
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tarea_metadata_id:
                    referencedColumnName: id
            orphanRemoval: false
        archivo:
            targetEntity: Archivo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                archivo_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
