ContadoresBundle\Entity\ArchivoTareaMetadata:
    type: entity
    table: archivo_tarea_metadata
    indexes:
        fk_archivo_tarea_metadata_archivo_idx:
            columns:
                - archivo_id
        fk_archivo_tarea_metadata_tarea_metada_idx:
            columns:
                - tarea_metadata_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        creationTime:
            type: datetime
            nullable: false
        updateTime:
            type: datetime
            nullable: false
    manyToOne:
        archivo:
            targetEntity: Archivo
            cascade: [ remove ]
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                archivo_id:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
        tareaMetadata:
            targetEntity: TareaMetadata
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: archivos
            joinColumns:
                tarea_metadata_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
