ContadoresBundle\Entity\ArchivoTarea:
    type: entity
    table: archivo_tarea
    indexes:
        fk_archivo_tarea_idx:
            columns:
                - archivo_id
        fk_tarea_archivo_idx:
            columns:
                - tarea_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    manyToOne:
        archivo:
            targetEntity: Archivo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                archivo_id:
                    referencedColumnName: id
            orphanRemoval: false
        tarea:
            targetEntity: Tarea
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tarea_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
