ContadoresBundle\Entity\EstadoSubTarea:
    type: entity
    table: estado_sub_tarea
    indexes:
        tipoEstado_estado_idx:
            columns:
                - tipo_estado_id
        subTarea_estado_sub_tarea_idx:
            columns:
                - sub_tarea_id
        contador_estado_tarea_idx:
            columns:
                - contador_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        fechaInicio:
            type: datetime
            nullable: false
            column: fecha_inicio
        fechaFin:
            type: datetime
            nullable: true
            column: fecha_fin
        horasTrabajadas:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: horas_trabajadas
    manyToOne:
        contador:
            targetEntity: Contador
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                contador_id:
                    referencedColumnName: id
                    onDelete: SET NULL
            orphanRemoval: false
        subTarea:
            targetEntity: SubTarea
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sub_tarea_id:
                    referencedColumnName: id
                    onDelete: SET NULL
            orphanRemoval: false
        tipoEstado:
            targetEntity: TipoEstado
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipo_estado_id:
                    referencedColumnName: id
                    onDelete: SET NULL
            orphanRemoval: false
    lifecycleCallbacks: {  }
