ContadoresBundle\Entity\ImpuestoCuil:
    type: entity
    table: impuesto_cuil
    indexes:
        impuestos_cuil_idx:
            columns:
                - impuesto_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        cuil:
            type: integer
            nullable: false
            options:
                unsigned: false
        mes:
            type: string
            nullable: false
            length: 12
            options:
                fixed: false
        fecha:
            type: date
            nullable: false
    manyToOne:
        impuesto:
            targetEntity: Impuesto
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                impuesto_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
