ContadoresBundle\Entity\Periodo:
    type: entity
    table: periodo
    indexes:
        fk_periodo_esquema_idx:
            columns:
                - esquema_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        fechaDesde:
            type: date
            nullable: false
            column: fecha_desde
        fechaHasta:
            type: date
            nullable: false
            column: fecha_hasta
    manyToOne:
        esquema:
            targetEntity: Esquema
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                esquema_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
