ContadoresBundle\Entity\TareaMetadata:
    type: entity
    table: tarea_metadata
    indexes:
        area_tareaMetadata_idx:
            columns:
                - area_id
        impuesto_tarea_idx:
            columns:
                - impuesto_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        esperiodica:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: esPeriodica
    manyToOne:
        impuesto:
            targetEntity: Impuesto
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                impuesto_id:
                    referencedColumnName: id
            orphanRemoval: false
        area:
            targetEntity: Area
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                area_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
