ContadoresBundle\Entity\TareaMetadata:
    type: entity
    table: tarea_metadata
    indexes:
        fk_rubro_tareaMeta_idx:
            columns:
                - rubro_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        esperiodica:
            type: boolean
            nullable: false
            options:
                default: '0'
            column: esPeriodica
        activo:
            type: boolean
            nullable: false
            options:
                default: '1'
            column: activo
    oneToMany:
        archivos:
            targetEntity: ArchivoTareaMetadata
            mappedBy: tareaMetadata
            orderBy: { 'updateTime': 'DESC'}
    manyToOne:
        rubro:
            targetEntity: Rubro
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                rubro_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
