ContadoresBundle\Entity\TipoEstado:
    type: entity
    table: tipo_estado
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        esEstadoFinal:
            type: boolean
            nullable: true
            options:
                default: '0'
            column: es_estado_final
    lifecycleCallbacks: {  }
