ContadoresBundle\Entity\Usuario:
    type: entity
    table: usuario
    indexes:
        rol_usuario_idx:
            columns:
                - rol_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        mail:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        entidadId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: entidad_id
        activo:
            type: boolean
            nullable: true
            options:
                default: '1'
    manyToOne:
        rol:
            targetEntity: Rol
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                rol_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
