archivocliente:
    pattern:  /
    defaults: { _controller: "ContadoresBundle:ArchivoCliente:index" }

archivocliente_show:
    pattern:  /{id}/show
    defaults: { _controller: "ContadoresBundle:ArchivoCliente:show" }

archivocliente_new:
    pattern:  /new
    defaults: { _controller: "ContadoresBundle:ArchivoCliente:new" }

archivocliente_create:
    pattern:  /create
    defaults: { _controller: "ContadoresBundle:ArchivoCliente:create" }
    requirements: { _method: post }

archivocliente_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ContadoresBundle:ArchivoCliente:edit" }

archivocliente_update:
    pattern:  /{id}/update
    defaults: { _controller: "ContadoresBundle:ArchivoCliente:update" }
    requirements: { _method: post|put }

archivocliente_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ContadoresBundle:ArchivoCliente:delete" }
    requirements: { _method: post|delete }
