archivosubtareametadata:
    pattern:  /
    defaults: { _controller: "ContadoresBundle:ArchivoSubTareaMetadata:index" }

archivosubtareametadata_show:
    pattern:  /{id}/show
    defaults: { _controller: "ContadoresBundle:ArchivoSubTareaMetadata:show" }

archivosubtareametadata_new:
    pattern:  /new
    defaults: { _controller: "ContadoresBundle:ArchivoSubTareaMetadata:new" }

archivosubtareametadata_create:
    pattern:  /create
    defaults: { _controller: "ContadoresBundle:ArchivoSubTareaMetadata:create" }
    requirements: { _method: post }

archivosubtareametadata_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ContadoresBundle:ArchivoSubTareaMetadata:edit" }

archivosubtareametadata_update:
    pattern:  /{id}/update
    defaults: { _controller: "ContadoresBundle:ArchivoSubTareaMetadata:update" }
    requirements: { _method: post|put }

archivosubtareametadata_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ContadoresBundle:ArchivoSubTareaMetadata:delete" }
    requirements: { _method: post|delete }
