archivosubtarea:
    pattern:  /
    defaults: { _controller: "ContadoresBundle:ArchivoSubTarea:index" }

archivosubtarea_show:
    pattern:  /{id}/show
    defaults: { _controller: "ContadoresBundle:ArchivoSubTarea:show" }

archivosubtarea_new:
    pattern:  /new
    defaults: { _controller: "ContadoresBundle:ArchivoSubTarea:new" }

archivosubtarea_create:
    pattern:  /create
    defaults: { _controller: "ContadoresBundle:ArchivoSubTarea:create" }
    requirements: { _method: post }

archivosubtarea_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ContadoresBundle:ArchivoSubTarea:edit" }

archivosubtarea_update:
    pattern:  /{id}/update
    defaults: { _controller: "ContadoresBundle:ArchivoSubTarea:update" }
    requirements: { _method: post|put }

archivosubtarea_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ContadoresBundle:ArchivoSubTarea:delete" }
    requirements: { _method: post|delete }
