cliente:
    pattern:  /
    defaults: { _controller: "ContadoresBundle:Cliente:index" }

cliente_show:
    pattern:  /{id}/show
    defaults: { _controller: "ContadoresBundle:Cliente:show" }

cliente_new:
    pattern:  /new
    defaults: { _controller: "ContadoresBundle:Cliente:new" }

cliente_create:
    pattern:  /create
    defaults: { _controller: "ContadoresBundle:Cliente:create" }
    requirements: { _method: post }

cliente_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ContadoresBundle:Cliente:edit" }

cliente_update:
    pattern:  /{id}/update
    defaults: { _controller: "ContadoresBundle:Cliente:update" }
    requirements: { _method: post|put }

cliente_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ContadoresBundle:Cliente:delete" }
    requirements: { _method: post|delete }

cliente_tareas:
    pattern:  /tareas
    defaults: { _controller: "ContadoresBundle:Cliente:tareasTodas" }

cliente_pendientes:
    pattern:  /pendientes
    defaults: { _controller: "ContadoresBundle:Cliente:tareasPendientes" }