estadosubtarea:
    pattern:  /
    defaults: { _controller: "ContadoresBundle:EstadoSubTarea:index" }

estadosubtarea_show:
    pattern:  /{id}/show
    defaults: { _controller: "ContadoresBundle:EstadoSubTarea:show" }

estadosubtarea_new:
    pattern:  /new
    defaults: { _controller: "ContadoresBundle:EstadoSubTarea:new" }

estadosubtarea_create:
    pattern:  /create
    defaults: { _controller: "ContadoresBundle:EstadoSubTarea:create" }
    requirements: { _method: post }

estadosubtarea_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ContadoresBundle:EstadoSubTarea:edit" }

estadosubtarea_update:
    pattern:  /{id}/update
    defaults: { _controller: "ContadoresBundle:EstadoSubTarea:update" }
    requirements: { _method: post|put }

estadosubtarea_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ContadoresBundle:EstadoSubTarea:delete" }
    requirements: { _method: post|delete }
