tarea:
    pattern:  /
    defaults: { _controller: "ContadoresBundle:Tarea:index" }

tarea_show:
    pattern:  /{id}/show
    defaults: { _controller: "ContadoresBundle:Tarea:show" }

tarea_new:
    pattern:  /new
    defaults: { _controller: "ContadoresBundle:Tarea:new" }

tarea_periodica_new:
    pattern:  /periodicanew
    defaults: { _controller: "ContadoresBundle:Tarea:newPeriodica" }

tarea_realizada:
    pattern:  /realizada
    defaults: { _controller: "ContadoresBundle:Tarea:realizada" }

tarea_finalizar:
    pattern:  /{id}/finalizar
    defaults: { _controller: "ContadoresBundle:Tarea:finalizar" }

tarea_create:
    pattern:  /create
    defaults: { _controller: "ContadoresBundle:Tarea:create" }
    requirements: { _method: post }

tarea_periodica_create:
    pattern:  /periodicacreate
    defaults: { _controller: "ContadoresBundle:Tarea:createPeriodica" }
    requirements: { _method: post }

tarea_realizada_create:
    pattern:  /realizadacreate
    defaults: { _controller: "ContadoresBundle:Tarea:createRealizada" }
    requirements: { _method: post }

tarea_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ContadoresBundle:Tarea:edit" }

tarea_update:
    pattern:  /{id}/update
    defaults: { _controller: "ContadoresBundle:Tarea:update" }
    requirements: { _method: post|put }

tarea_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ContadoresBundle:Tarea:delete" }
    requirements: { _method: post|delete }

tarea_cliente_show:
    pattern:  /{id}/showcliente
    defaults: { _controller: "ContadoresBundle:Tarea:showCliente" }

tarea_agendar_new:
    pattern:  /agendarnew
    defaults: { _controller: "ContadoresBundle:Tarea:newAgendar" }

tarea_agendar_create:
    pattern:  /agendarcreate
    defaults: { _controller: "ContadoresBundle:Tarea:createAgendar" }

tarea_dar_de_baja:
    pattern:  /{id}/dar_de_baja
    defaults: { _controller: "ContadoresBundle:Tarea:darDeBaja" }
    requirements: { _method: post|delete }
