services:
#    contadores.example:
#        class: ContadoresBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
      contadores.servicios.tareas:
          class: ContadoresBundle\Servicios\TareasService
          arguments:
              entityManager: @doctrine.orm.entity_manager
              us: @contadores.servicios.usuario
      contadores.servicios.usuario:
          class: ContadoresBundle\Servicios\UsuarioService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      contadores.servicios.cliente:
          class: ContadoresBundle\Servicios\ClienteService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      contadores.servicios.bajaAdministrativa:
          class: ContadoresBundle\Servicios\BajaAdministrativaService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      contadores.servicios.vencimiento:
          class: ContadoresBundle\Servicios\VencimientoService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      contadores.servicios.filtro:
          class: ContadoresBundle\Servicios\FiltroService
          arguments:
              entityManager: @doctrine.orm.entity_manager
      contadores.servicios.archivo:
          class: ContadoresBundle\Servicios\ArchivoService
          arguments:
              filesystem: @archivos_filesystem
              entityManager: @doctrine.orm.entity_manager
