Hera\ContadoresBundle\Entity\ArchivoTareaMetadata:
    type: entity
    table: archivo_tarea_metadata
    indexes:
        usuario_archivoTM_idx:
            columns:
                - usuario_id
        tareaMetadata_archivo_idx:
            columns:
                - tarea_metadata_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        ruta:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
    manyToOne:
        tareaMetadata:
            targetEntity: TareaMetadata
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                tarea_metadata_id:
                    referencedColumnName: id
            orphanRemoval: false
        usuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
