Hera\ContadoresBundle\Entity\Contador:
    type: entity
    table: contador
    indexes:
        usuario_contador_idx:
            columns:
                - usuario_id
        IDX_E83EF8FABD0F409C:
            columns:
                - area_id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        apellido:
            type: string
            nullable: false
            length: 45
            options:
                fixed: false
        celular:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        mail:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        telefono:
            type: string
            nullable: true
            length: 45
            options:
                fixed: false
        esJefe:
            type: boolean
            nullable: true
            options:
                default: '0'
            column: es_jefe
    manyToOne:
        area:
            targetEntity: Area
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                area_id:
                    referencedColumnName: id
            orphanRemoval: false
        usuario:
            targetEntity: Usuario
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
